/**
 * Terminverwaltungssystem
 * Schnittstelle des Terminverwaltungssystem für Impfterminen in Hausarztpraxen
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maximiliangruber91@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Meeting {
    meetingId?: number;
    meetingDateTime?: Date;
    firstname?: string;
    lastname?: string;
    /**
     * Meeting Status
     */
    status?: Meeting.StatusEnum;
}
export namespace Meeting {
    export type StatusEnum = 'aktiv' | 'inaktiv';
    export const StatusEnum = {
        Aktiv: 'aktiv' as StatusEnum,
        Inaktiv: 'inaktiv' as StatusEnum
    }

}
